SalesWebCafeteria/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SalesWebCafeteria.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SalesWebCafeteria/Controllers/LancheController.cs
using Microsoft.AspNetCore.Mvc;
using SalesWebCafeteria.Models;
using SalesWebCafeteria.Models.ViewModels;
using SalesWebCafeteria.Repository.Interfaces;

namespace SalesWebCafeteria.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                if (string.Equals("Paes Salgados", categoria, StringComparison.OrdinalIgnoreCase))
                {
                    lanches = _lancheRepository.Lanches
                        .Where(l => l.Categoria.CategoriaNome.Equals("Paes Salgados"))
                        .OrderBy(l => l.LancheId);
                }
                else
                {
                    lanches = _lancheRepository.Lanches
                        .Where(l => l.Categoria.CategoriaNome.Equals("Paes Doces"))
                        .OrderBy(l => l.LancheId);
                }
                categoriaAtual = categoria;
            }
            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);

            /* ViewData["Titulo"] = "Cardápio";
             ViewData["Data"] = DateTime.Now; 

             var lanches = _lancheRepository.Lanches;
             var totalLanches = lanches.Count();

             ViewBag.Total = "Total Disponíveis: ";
             ViewBag.totalLanches = totalLanches;

             return View(lanches); */



        }





    }
}

SalesWebCafeteria/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/carousel11.jpg" width="700px" height="300px" alt="">
            <div class="carousel-caption  d-none d-md-block">
                <h3>
                    <small class ="text-white"></small>
                </h3>
                <p>Receita da Casa</p>
            </div>
        </div>

        <div class="carousel-item">
            <img src="~/images/carousel12.jpg" width="700px" height="300px" alt="">
            <div class="carousel-caption d-none d-md-block">
                <h3>
                    <small class="text-white">Combos Especiais</small>
                </h3>
                <p><p /> <p></p>
            </div>
        </div>

        <div class="carousel-item">
            <img src="~/images/carousel13.jpg" width="700px" height="300px" alt="">
            <div class="carousel-caption d-none d-md-block">
                <h3></h3>
                <p>Variedade de Sabores.<p />  <p><p />
            </div>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

</div>

SalesWebCafeteria/Views/Shared/_LanchesRasumoPartial.cshtml
@model  Lanche

<div class="col-sm-4 col-md-4 col-lg-4">
    <h3>@Model.Nome</h3>
    <p><img src="@Model.ImagemUrl" class="img-fluid"></p>
    <h5>Valor: R$@Model.Preco.ToString("F2", CultureInfo.InvariantCulture)</h5>
    <p>
        <h6>Ingredientes:<br />@Model.DescricaoCurta</h6>
    </p>
</div>

SalesWebCafeteria/Views/Shared/_LanchesResumoPartial.cshtml
@model  Lanche

<div class="col-sm-4 col-md-4 col-lg-4">
    <h3>@Model.Nome</h3>
    <p><img src="@Model.ImagemUrl" class="img-fluid"></p>
    <h5>Valor: R$@Model.Preco.ToString("F2", CultureInfo.InvariantCulture)</h5>
    <p>
        <h6>Ingredientes:<br />@Model.DescricaoCurta</h6>
    </p>
</div>

SalesWebCafeteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -BigLanches&Cafés</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SalesWebCafeteria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">

                <img src="~/images/fast-food-outline.svg" height="40" width="40" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BigLanches&Cafés</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dropdown" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dropdown" asp-area="" asp-controller="Lanche" asp-action="List">Cardápio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dropdown" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <form class="d-flex">
                            <input class="form-control me-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </ul>
                    @* Carrinho-icon*@
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                </div>
            </div>
        </nav>
    </header>
    <br />



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BigLanches&Cafés - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>